name: Strict confinement test Microk8s
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s with strict confinement
    steps:
    - uses: balchua/microk8s-actions@master
      with:
        channel: '1.25-strict/stable'
        addons: '["rbac", "dns", "storage", "registry", "metrics-server"]'
    - name: Test MicroK8s commands
      id: microk8s-commands
      run: |
        set -ex
        microk8s status        
        microk8s kubectl get pods -A
