name: Strict confinement test Microk8s
on: [push]

jobs:
  test:
    strategy:
      matrix:
        version:
          ["1.25-strict/stable", "1.26-strict/stable", "1.27-strict/stable"]
    runs-on: ubuntu-latest
    name: A job to install MicroK8s with strict confinement
    steps:
      - uses: balchua/microk8s-actions@master
        with:
          channel: "${{ matrix.version }}"
          devMode: "true"
          addons: '[ "dns", "hostpath-storage"]'
      - name: Test MicroK8s commands
        id: microk8s-commands
        run: |
          set -ex
          sudo microk8s status        
          sudo microk8s kubectl get pods -A
